"""
Project TenantPlus — Backend Pydantic v2 Schemas (PHASE 2)
Module: backend.schemas

Defines the exact structured output contracts for Google Antigravity Agent
and the deterministic rules engine.
"""

from typing import List, Optional
from pydantic import BaseModel, Field, field_validator
from datetime import date


class BoundingBox(BaseModel):
    """
    Normalized spatial bounding box coordinates for key clauses.
    Values are normalized from 0.0 to 1.0 (or scaled up to 1000).
    (ymin, xmin) = top-left corner, (ymax, xmax) = bottom-right corner.
    """
    ymin: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Normalized top edge coordinate [0.0, 1.0]"
    )
    xmin: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Normalized left edge coordinate [0.0, 1.0]"
    )
    ymax: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Normalized bottom edge coordinate [0.0, 1.0]"
    )
    xmax: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Normalized right edge coordinate [0.0, 1.0]"
    )
    label: Optional[str] = Field(
        default=None,
        description="Optional clause label, e.g., 'SERVICE_DATE' or 'DEMANDED_AMOUNT'"
    )
    text_content: Optional[str] = Field(
        default=None,
        description="Extracted OCR text contained within the bounding region"
    )


class NoticeExtraction(BaseModel):
    """
    Structured extraction payload generated by Google Antigravity Agent / Gemini Vision.
    CRITICAL: Contains ONLY extracted document facts and coordinates.
    Mathematical calculations are strictly forbidden in this model.
    """
    notice_type: str = Field(
        ...,
        description="Exact notice type or title detected on document, e.g. '3-Day Notice to Pay or Quit'"
    )
    service_date: str = Field(
        ...,
        description="Date the notice was served in ISO 8601 YYYY-MM-DD format"
    )
    demanded_amount: float = Field(
        ...,
        ge=0.0,
        description="Total monetary demand stated on the face of the notice"
    )
    date_bounding_box: BoundingBox = Field(
        ...,
        description="Normalized bounding box mapping the service date clause on the document"
    )
    amount_bounding_box: BoundingBox = Field(
        ...,
        description="Normalized bounding box mapping the demanded rent amount on the document"
    )
    extracted_text_blocks: List[str] = Field(
        default_factory=list,
        description="Verbatim text blocks from the notice used for statutory warning substring verification"
    )

    @field_validator("service_date")
    @classmethod
    def validate_iso_date(cls, v: str) -> str:
        try:
            date.fromisoformat(v)
            return v
        except ValueError:
            return date.today().isoformat()
